### ISSUE TITLE
Bad URL &  SyntaxError

### ISSUE THREAD

**Issue by drscotthawley** [mathisonian/idyll-animation-article#1]
Hi. I'm having trouble trying to follow this, and hit a bad link while reading the page.

 The link for the context API 404's. 
> In those cases we can supply a custom tweening function via [Idyll’s context API](https://idyll-lang.org/docs/advanced-configuration) to create custom animations using JavaScript.

Following the instructions for installation and running goes like this on Ubuntu 20.10:

```bash 
$ git clone https://github.com/mathisonian/idyll-animation-article.git
Cloning into 'idyll-animation-article'...
remote: Enumerating objects: 23, done.
remote: Total 23 (delta 0), reused 0 (delta 0), pack-reused 23
Unpacking objects: 100% (23/23), 83.74 KiB | 974.00 KiB/s, done.
$ cd idyll-animation-article.git
$ npm i -g idyll
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/idyll
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/idyll/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/idyll/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-youtube@7.13.0 requires a peer of @types/youtube@^0.0.38 but none is installed. You must install peer dependencies yourself.
npm WARN react-tooltip@3.11.6 requires a peer of react@>=^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-tooltip@3.11.6 requires a peer of react-dom@>=^16.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/idyll
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/idyll'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/idyll'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/idyll'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shawley/.npm/_logs/2020-11-17T01_03_25_718Z-debug.log

$ sudo npm i -g idyll
[sudo] password for shawley: 
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/idyll -> /usr/local/lib/node_modules/idyll/bin/idyll.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/idyll/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-youtube@7.13.0 requires a peer of @types/youtube@^0.0.38 but none is installed. You must install peer dependencies yourself.
npm WARN react-tooltip@3.11.6 requires a peer of react@>=^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-tooltip@3.11.6 requires a peer of react-dom@>=^16.0.0 but none is installed. You must install peer dependencies yourself.

+ idyll@4.12.1
updated 1 package in 18.523s

$ sudo npm i
npm WARN animation-example@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.6 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 981 packages from 855 contributors and audited 1008 packages in 10.522s
found 640 vulnerabilities (353 low, 10 moderate, 277 high)
  run `npm audit fix` to fix them, or `npm audit` for details


$ idyll

Building Idyll project with output directory: build

/home/shawley/Downloads/idyll/idyll-animation-article/context.js:1
import TWEEN from 'tween.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .js] (/home/shawley/Downloads/idyll/idyll-animation-article/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.Module._load (/home/shawley/Downloads/idyll/idyll-animation-article/node_modules/idyll/src/node-config.js:23:29)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at exports.getHTML (/home/shawley/Downloads/idyll/idyll-animation-article/node_modules/idyll/src/pipeline/parse.js:156:19)
    at /home/shawley/Downloads/idyll/idyll-animation-article/node_modules/idyll/src/pipeline/index.js:81:25
    at tryCatcher (/home/shawley/Downloads/idyll/idyll-animation-article/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/shawley/Downloads/idyll/idyll-animation-article/node_modules/bluebird/js/release/method.js:39:29)
    at /home/shawley/Downloads/idyll/idyll-animation-article/node_modules/idyll/src/pipeline/index.js:37:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

Going back and running `npm audit fix`, even with `sudo` and even with `--force` never produced anything that resolved the syntax error. 

I also tried pasting the tutorial code in the Idyll online editor, and got 
```
Error parsing input at line 16, column 27

          new TWEEN.Tween(_tween)
                        ^^^
```

What to try next?  Thanks.

**Comment by mathisonian** [comment]
Hey @drscotthawley it seems like you may be using an old version of node.js. I would recommend installing using the nvm (node version manager) tool https://github.com/nvm-sh/nvm. If you install this way you won't run into the sudo errors you are hitting above, and can easily update/change node versions.

The "import" syntax should be available in any version >= 13. If you need to stick with the older version you can change the import syntax to use require, `const TWEEN = require('tween.js');` is the equivalent statement using require.

Thanks for the heads up on the 404, I will add a redirect to the docs to make sure that link forwards to the correct place.
